In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [5]:
bank_loan_approval_dataset = pd.read_csv(
    csv_path if "csv_path" in globals() else "feed/bank_loan_approval_dataset.csv"
)

bank_loan_approval_dataset.head()

,application_id,first_name,last_name,age,employment_type,employment_years,annual_income,credit_score,debt_to_income_ratio,savings_balance,existing_loans_count,missed_payments_12m,home_ownership,loan_purpose,loan_term_months,interest_rate,requested_loan_amount,loan_approved,loan_approved decision,approved_loan_amount
0,APP00001,Aarav0001,Adams0001,25,Salaried,0,42963.81,672,0.169,35540.30,0,0,Rent,Business,24,13.65,10901.07,0,No,0.00
1,APP00002,Aiden0002,Baker0002,55,Salaried,27,90949.60,643,0.313,9760.72,3,0,Rent,Business,48,14.35,24216.29,1,Yes,16041.35
2,APP00003,Amara0003,Brooks0003,50,Salaried,24,60941.84,748,0.476,53373.76,2,0,Mortgage,Personal,72,13.05,29579.03,1,Yes,19484.45
3,APP00004,Bella0004,Carter0004,40,Salaried,11,52830.38,660,0.115,17127.76,0,0,Rent,Education,12,12.48,28667.75,0,No,0.00
4,APP00005,Caleb0005,Coleman0005,40,Business Owner,18,57200.50,654,0.465,32561.08,2,0,Rent,Medical,12,14.00,27119.93,1,Yes,15375.22

In [11]:
bank_loan_approval_dataset2.columns

Index(['application_id', 'first_name', 'last_name', 'age', 'employment_type',
       'employment_years', 'annual_income', 'credit_score',
       'debt_to_income_ratio', 'savings_balance', 'existing_loans_count',
       'missed_payments_12m', 'home_ownership', 'loan_purpose',
       'loan_term_months', 'interest_rate', 'requested_loan_amount',
       'loan_approved', 'loan_approved decision', 'approved_loan_amount'],
      dtype='object')

In [7]:
bank_loan_approval_dataset2 =  bank_loan_approval_dataset.copy()
bank_loan_approval_dataset2.shape,bank_loan_approval_dataset.shape

((1000, 20), (1000, 20))

In [ ]:
numeric_cols = bank_loan_approval_dataset2[[
    "employment_years",
    "annual_income",
    "credit_score",
    "debt_to_income_ratio",
    "savings_balance",
    "existing_loans_count",
    "missed_payments_12m",
    "requested_loan_amount",
    "age",
]]

In [12]:
non_numeric_cols = bank_loan_approval_dataset2[[
    "employment_years",
    "annual_income",
    "credit_score",
    "debt_to_income_ratio",
    "savings_balance",
    "existing_loans_count",
    "missed_payments_12m",
    "requested_loan_amount",
    "age",
    "home_ownership",
    "loan_purpose",
]]

In [13]:
non_numeric_cols.head()

,employment_years,annual_income,credit_score,debt_to_income_ratio,savings_balance,existing_loans_count,missed_payments_12m,requested_loan_amount,age,home_ownership,loan_purpose
0,0,42963.81,672,0.169,35540.30,0,0,10901.07,25,Rent,Business
1,27,90949.60,643,0.313,9760.72,3,0,24216.29,55,Rent,Business
2,24,60941.84,748,0.476,53373.76,2,0,29579.03,50,Mortgage,Personal
3,11,52830.38,660,0.115,17127.76,0,0,28667.75,40,Rent,Education
4,18,57200.50,654,0.465,32561.08,2,0,27119.93,40,Rent,Medical

In [14]:
numeric_cols.head()

,employment_years,annual_income,credit_score,debt_to_income_ratio,savings_balance,existing_loans_count,missed_payments_12m,requested_loan_amount,age
0,0,42963.81,672,0.169,35540.30,0,0,10901.07,25
1,27,90949.60,643,0.313,9760.72,3,0,24216.29,55
2,24,60941.84,748,0.476,53373.76,2,0,29579.03,50
3,11,52830.38,660,0.115,17127.76,0,0,28667.75,40
4,18,57200.50,654,0.465,32561.08,2,0,27119.93,40

In [15]:
target = bank_loan_approval_dataset2[[
    "requested_loan_amount"
]]

In [16]:
target.head()

   requested_loan_amount
0               10901.07
1               24216.29
2               29579.03
3               28667.75
4               27119.93

In [17]:
numeric_cols.head()

,employment_years,annual_income,credit_score,debt_to_income_ratio,savings_balance,existing_loans_count,missed_payments_12m,requested_loan_amount,age
0,0,42963.81,672,0.169,35540.30,0,0,10901.07,25
1,27,90949.60,643,0.313,9760.72,3,0,24216.29,55
2,24,60941.84,748,0.476,53373.76,2,0,29579.03,50
3,11,52830.38,660,0.115,17127.76,0,0,28667.75,40
4,18,57200.50,654,0.465,32561.08,2,0,27119.93,40